extends Node

enum Language {DE, EN}

enum InputMotion {INPUT_ALLOWED, INPUT_FREEZED, INPUT_NOT_ALLOWED}
enum PlayerType {NPC, MAIN, PARTY}
enum CharStyle {NONE, MC01, MC02, MC03}
enum CharClass {FIGHTER, HEALER, MAGE, THIEF}
enum MovedBy {NOTHING, EVENT, PLAYER}
enum Direction {D000, D045, D090, D135, D180, D225, D270, D315, NOTHING}
enum InstructionType {NONE, RESOLUTION, TEST}
enum ItemType {INVALID, QUEST, USABLE, WEAPON, SHIELD, ARMOR, ACCESSOIRES, CRAFT}
enum WeaponType {NO_TYPE, SWORD, BOW, MACE, AXE}
enum ShieldsType{NO_TYPE, SMALL_SHIELD , HUGE_SHIELD}
enum ArmorType {NO_TYPE, LIGHT_ARMOR, HEAVY_ARMOR, ROBES, LEATHER}
enum AccessoiresType {NO_TYPE, RING, AMULET, BRACELET}
enum CraftType {NO_TYPE, CRYSTAL, HERB, ELEMENT, METAL, WOOD, SPIRIT}

enum Quest {NONE, XXX}

enum CharControlID {SOMETHING_ELSE, PLAYER1, PLAYER2, PLAYER3}

enum BattleMode {NO_BATTLE, INITIATED, ONGOING, DURING_ATTACK, PAUSED}

enum GameStatus {TITEL, MENU, NORMAL, BATTLE, BATTLE_MENUE, PAUSE}

enum FadeInDirection {NONE, TOP, TOP_LEFT, LEFT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT, RIGHT, TOP_RIGHT}
